### ISSUE TITLE
Tracking Issue: Automated Test/Support Coverage Reporting

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/seal5#116]
As discussed on Friday, we need an (automated) flow to track and report which kinds of instructions are currently being supported by Seal5. As the project is quite ambitious, I came up with a number of sub-tasks which can be implemented on individually.

**Tasks**

1. Properties of Instructions
- [x] #118
- [x] #117

2. Status/Support of Instructions in Seal5 Flow
- [x] #119
- [x] #120

3. Tracking LLVM Test Results
- [x] #128
- [x] #121
- [x] #122
- [x] #123
- [x] #143
- ~~[ ] Define test files in Seal5 settings~~

4. Analysis and Grouping
- [x] #136
- [x] #139
- [x] #140
- [x] #141
- [x] Integration of Test Coverage Data in Tables

5. Generation of Reports
- [x] #137
- ~~[ ] Pick suitable visualization tool~~
- [x] Generate Reports
- [x] Publish reports

6. Automation (CI/CD)
- [x] Define triggers (weekly/push/tag/…)
- [x] #130
- [x] #131
- [x] #132
- [x] Add workflows to refresh/release reports
- ~~[ ] GitHub Pages integration?~~

7. Miscellaneous 
- [ ] #133
- [x] #129
- [ ] #18
- [x] Increase number of example instructions/extensions

**Comment by PhilippvK** [comment]
@thomasgoodfellow @dlr-jas @kebi-be @AndHager Feel free to add any comments or assign any tasks you would like to work on.

Tomorrow I can share some more notes!

**Comment by PhilippvK** [comment]
I am making good progress. 

@thomasgoodfellow @kebi-be @dlr-jas 
Using the example CSV snippes I have posted in #117, #120 & #123 you should be able to get started with Task 4. & 5.

I will start working on some CI/CD changes to generate the CSVs automatically and look into adding more test cases!

**Comment by PhilippvK** [comment]
@kebi-be @dlr-jas @thomasgoodfellow @AndHager 

I made quite good progress this week:
- Fixed broken Core-V Demo
- Fixed broken unit tests
- Implemented more unit tests
- Generate raw data artifacts in reports
- Write data as markdown to Workflow Summary 

See here for the recent run: https://github.com/tum-ei-eda/seal5/actions/runs/11630150544

Based on this, we you can always get the latest csv files by downloading the `demo-*-reports` artifact. Since the data  is already available, it should be easy to do the combination/analysis and generation of the final reports in a CI job.

Further, I added more properties which should help grouping/filtering the instructions:
- `enc_size`: 16/32/48bit 
- `is_compressed`: enc_size == 16
- `op_code`: (OP-IMM, LOAD, custom-0,…)
- `enc_format`: (r-type, i-type, …)
- `{uses,defs}_custom_reg`: in case non-GPR registers are used, we can not generate patterns
- `has_imm_leaf` (not pushed yet): If the behavior contains operations on immediate inputs which can be constant folded, the generated pattern will never match. This detection should let us skip the pattern-gen stage for incompatible instructions.

**Comment by kebi-be** [comment]
Currently using the examples of the OpenASIP_base for Task4 and Task5. This concept will be used for analysing the data in the CI as mentioned by @PhilippvK

**Comment by kebi-be** [comment]
@PhilippvK: There is an error in the "test_results.cvs"data from the  https://github.com/tum-ei-eda/seal5/actions/runs/11630150544 which results to error when merging the files.  Used the corev demo reports.
Columns: **model_name**,set,xlen,instr,test_kind,test_file,test_fmt,result,**model** 
Fix: rename **model_name** to **model** and delete redundant column "**model**" at the end

**Comment by PhilippvK** [comment]
I will take care of this today, thanks!

**Comment by PhilippvK** [comment]
> @PhilippvK: There is an error in the "test_results.cvs"data from the https://github.com/tum-ei-eda/seal5/actions/runs/11630150544 which results to error when merging the files. Used the corev demo reports.
Columns: model_name,set,xlen,instr,test_kind,test_file,test_fmt,result,model
Fix: rename model_name to model and delete redundant column "model" at the end

Fixed!

**Comment by PhilippvK** [comment]
I will close this as all remaining steps can be discusses in the related separate issues.

Thank you for your help @kebi-be!
