### ISSUE TITLE
Skip PatternGen for unsupported Instructions

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/seal5#147]
The pattern-gen (and cdsl2llvmir) pass should be skipped if the instruction is not supported for pattern generation.

**This is the case for:**
- [x] Multiple destination registers
- [x] Zero source registers
- [x] Missing Behavior Block (not-implemented)
- [x] Usage of custom registers (See #38)
- [x] Memory instructions (See #25)
- [x] Branch instructions (See #23 )
- [ ] Control Flow instructions (#57 should help here)
- [x] ImmLeaf Instructions (See #146)
