### ISSUE TITLE
Support memory instrinsics/builtins

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/seal5#150]
**Tasks:**
- [ ] #25 (@PhilippvK )
- [ ] Create example CoreDSL + YAML for memory instruction (RV32I base or XCVMem)
- [ ] Figure out required patches (Pointer types, predicates,...)
- [ ] Update Seal5 to generate patches for emitting intrinsics for memory operations
